server {
    listen 5173;
    server_name localhost;
    server_tokens off;

    location / {
        proxy_pass http://client_admin:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}