server {
    listen 5173;
    server_name localhost;

    # 1. Admin React Website
    location / {
        proxy_pass http://client_admin:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 2. Backend API (Admin needs this too!)
    location /api/ {
        # THE TRAILING SLASH IS CRITICAL HERE:
        proxy_pass http://server:5000/;  
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}