services:
  server:
    build:
      context: ./Server
      dockerfile: ../Docker/dockerfile.server
    ports:
      - "3000:3000"
    env_file:
      - ./Server/.env
    
  client_admin:
    build:
      context: ./Client_admin
      dockerfile: ../Docker/dockerfile.client_admin
    ports:
      - "5174:80"
    env_file:
      - ./Client_admin/.env
    depends_on:
      - server
    
  client_main:
    build:
      context: ./Client_main
      dockerfile: ../Docker/dockerfile.client_main
    ports:
      - "8080:80"
    env_file:
      - ./Client_main/.env
    depends_on:
      - server


      